-- GEMA Kritik & Saran
-- Jalankan di Supabase SQL Editor setelah setup Galeri Karya.

create table if not exists public.gema_feedback (
  id bigint generated by default as identity primary key,
  name text,
  role text not null,
  institution text,
  feature text not null,
  rating integer not null check (rating between 1 and 5),
  positive text,
  criticism text,
  suggestion text not null,
  contact text,
  created_at timestamptz not null default now()
);

alter table public.gema_feedback enable row level security;

-- Publik hanya boleh mengirim masukan.
drop policy if exists "Public can submit feedback" on public.gema_feedback;
create policy "Public can submit feedback"
on public.gema_feedback
for insert
to anon, authenticated
with check (true);

-- Tidak dibuat policy SELECT untuk publik.
-- Artinya data kritik/saran tidak bisa dibaca dari website menggunakan anon key.
-- Admin tetap dapat melihat data melalui Dashboard Supabase.

create index if not exists gema_feedback_created_at_idx
on public.gema_feedback(created_at desc);
