-- GEMA Galeri Karya — Supabase setup
-- Jalankan seluruh script ini di Supabase SQL Editor.

create table if not exists public.gema_gallery (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 2 and 120),
  creator text not null check (char_length(creator) between 2 and 80),
  institution text,
  category text not null check (category in ('Visual Edukatif','Media Interaktif','Game Edukatif','Lab Maya')),
  level text not null check (level in ('SD/MI','SMP/MTs','SMA/MA/SMK','Umum')),
  subject text,
  platform text,
  work_url text not null,
  thumbnail_url text,
  description text not null check (char_length(description) between 2 and 420),
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.gema_gallery enable row level security;

drop policy if exists "Public can read gallery" on public.gema_gallery;
create policy "Public can read gallery"
on public.gema_gallery
for select
to anon, authenticated
using (is_public = true);

drop policy if exists "Public can submit gallery" on public.gema_gallery;
create policy "Public can submit gallery"
on public.gema_gallery
for insert
to anon, authenticated
with check (is_public = true);

create index if not exists gema_gallery_created_at_idx
on public.gema_gallery(created_at desc);

create index if not exists gema_gallery_category_idx
on public.gema_gallery(category);

-- Catatan:
-- Public tidak diberi izin UPDATE atau DELETE.
-- Jika ingin moderasi, tambahkan kolom approved boolean default false,
-- ubah policy SELECT menjadi is_public = true AND approved = true,
-- lalu approve karya melalui dashboard Supabase.
